### PR TITLE
Added package.json for npm compatibility

### PR DESCRIPTION
**Pull request by nortonprojects**

### CODE REVIEW

**Comment by PawelDecowski** [comment]
You shouldn’t add `node_modules` directory to source control. The whole point of `package.json` is it lists dependencies that need to be installed for this package to work.

**Comment by nortonprojects** [comment]
Whoops, forgot to check .gitignore for them

**Comment by uncle9999** [comment]
#133

**Comment by uncle9999** [comment]
#90

**Comment by uncle9999** [comment]
@PawelDecowski

**Comment by uncle9999** [comment]
#2

**Pull request closed without merging**
