### PR TITLE
Feature/allow adding new card types

### PR DESCRIPTION
**Pull request by jaiprakashkhowal**
I added the feature to add new card-types using options parameter if user had the details(Name, Range and Length ) about the card.

Also add an example to test it

If You find it good please merge it.

### CODE REVIEW

**Comment by phpspider** [comment]
Any update on this pull request? @PawelDecowski

**Comment by PawelDecowski** [comment]
I’ll consider it for the next version when I get around to it.

**Comment by phpspider** [comment]
Thanks for the info. What's the plan for next version?

**Comment by unel** [comment]
Any update?

**Comment by PawelDecowski** [comment]
There wasn’t much interest in this feature so it hasn’t been accepted yet.

**Pull request closed without merging**
