### PR TITLE
elo card discovery + tests

### PR DESCRIPTION
**Pull request by pawlik**
I searched the web for official specs of Elo card but found nothing, there's only regexp for discovering it on some implementation pages. We use it since more than a year on eset brasil checkout page, so should be ok ;)

### CODE REVIEW

**Comment by douggr** [comment]
This will not cover all Elo ranges. Please don't merge.

**Comment by douggr** [comment]
Elo would include the ranges bellow:

```php
$PATTERN_ELO = implode('|', [
    '401178',
    '401179',
    '431274',
    '438935',
    '451416',
    '457393',
    '457631',
    '457632',
    '504175',
    '627780',
    '636297',
    '636368',
    '637095',

    //  - between 509000 through 509999
    '(509[0-9]{3})',

    //  - between 506699 through 506778
    '(506699|5067[0-6]\d|50677[0-8])',

    //  - between 650031 through 650033
    '(65003[1-3])',

    //  - between 650035 through 650051
    '(65003[5-9]|65004\d|65005[0-1])',

    //  - between 650405 through 650439
    '(65040[5-9]|6504[1-3]\d)',

    //  - between 650485 through 650538
    '(65048[5-9]|65049\d|6505[0-2]\d|65053[0-8])',

    //  - between 650541 through 650598
    '(65054[1-9]|6505[5-8]\d|65059[0-8])',

    //  - between 650700 through 650718
    '(65070\d|65071[0-8])',

    //  - between 650720 through 650727
    '(65072[0-7])',

    //  - between 650901 through 650920
    '(65090[1-9]|65091\d|650920)',

    //  - between 651652 through 651679
    '(65165[2-9]|6516[6-7]\d)',

    //  - between 655000 through 655019
    '(65500\d|65501\d)',

    //  - between 655021 through 655058﻿
    '(65502[1-9]|6550[3-4]\d|65505[0-8])',
]);
```

**Comment by thiagogsr** [comment]
I think [it](https://github.com/Fivell/credit_card_validations/blob/bf5ddfed273ce7aed8b5b453845e83ac467e654f/lib/data/brands.yaml#L244-L274) can help. When can it be merged?

**Comment by PawelDecowski** [comment]
@thiagogsr Looking at that source, it looks like Elo cards don’t have Luhn validation. If that’s the case, it can’t be added. Currently this plugin doesn’t have a mechanism for skipping Luhn check. And adding one would be a breaking change.

**Pull request closed without merging**
