### PR TITLE
add mir cards

### PR DESCRIPTION
**Pull request by MrKarad**
added support for mir cards.
https://en.wikipedia.org/wiki/Mir_(payment_system)

### CODE REVIEW

**Comment by PawelDecowski** [comment]
How did you get the `22-27` IIN range?

According to [Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_.28IIN.29) it’s only `2200–2204`.

**Comment by MrKarad** [comment]
I agree

**Comment by PawelDecowski** [comment]
Can you create a new pull request with the `release/1.2` instead of `master` as the base?

**Comment by MrKarad** [comment]
new pull request
https://github.com/PawelDecowski/jquery-creditcardvalidator/pull/118

**Pull request closed without merging**
