### PR TITLE
added a new validation to  new card flags

### PR DESCRIPTION
**Pull request by eder**
Hi! Today I needed use your plugin, but in my feature was necessary add a new type flag and new regexp.
Then I decided  share with other people. You can see this?

### CODE REVIEW

**Comment by PawelDecowski** [comment]
Thanks for contributing!

Can you share some references that show these prefixes indicate those cards?

**Comment by eder** [comment]
Of Course!! below see some links which i used as reference.
https://developers.ebanx.com/integrations/testing/credit-card-test-numbers
http://stackoverflow.com/a/23231321/286840
https://gist.github.com/claudiosmweb/26d9668f21dbdc787472

**Comment by PawelDecowski** [comment]
Fantastic. I’m not going to merge it, because in v1.1 the matching engine changes from regex to trie (you can preview it in the branch [feature/trie](https://github.com/PawelDecowski/jquery-creditcardvalidator/tree/feature/trie)). It’ll make specifying card prefixes much easier.

This will be included in v1.1.

**Comment by douggr** [comment]
refs #72

**Pull request closed without merging**
