### PR TITLE
Bug/broken diners detection

### PR DESCRIPTION
**Pull request by TerenceJohnson**
I have updated the Discover number ranges as per Discover's February 2017 Compliance Update, in addition to the Diners ranges added by @mac9416 

https://www.discovernetwork.com/downloads/IPP_VAR_Compliance.pdf

This partially addresses Issue #90 although the China UnionPay ranges are treated as Discover.

### CODE REVIEW

**Comment by steven-haddix** [comment]
Does it make sense to break out China UnionPay to a separate payment type since diners get broken out?

**Comment by TerenceJohnson** [comment]
Yes, it probably does make sense to have a different return value for UnionPay.

**Comment by steven-haddix** [comment]
I can try to put in an MR for this branch if you think it makes sense as a bug? Or address it in a separate MR.

**Comment by TerenceJohnson** [comment]
Go ahead and create a pull request if you have time to work on this now, otherwise I can make the change later in the week.

**Pull request closed without merging**
