### PR TITLE
Detect China Union Pay cards.

### PR DESCRIPTION
**Pull request by bukk530**
Addedd support for China Union Pay.
Testd with the following credit card numbers: https://developers.paymill.com/en/reference/testing/

### CODE REVIEW

**Comment by PawelDecowski** [comment]
Thanks @bukk530 

What’s the source that says cards starting with `62[0-5]` and length 13–16 are China Union Pay?

**Comment by bukk530** [comment]
My fault, the lenght is between 16-19, I fixed that in the new commit.

Sources:
http://www.richardsramblings.com/regex/credit-card-numbers/
http://en.wikipedia.org/wiki/Bank_card_number#Issuer_identification_number_.28IIN.29

**Comment by PawelDecowski** [comment]
Thanks again.

This will not make it into 1.0. The reason is China UnionPay card numbers aren’t Luhn-checksum valid and the validator currently doesn’t have a mechanism for skipping the Luhn validation.

**Comment by bukk530** [comment]
Check the new commit, I addedd a simple luhn skipping flag.

**Comment by PawelDecowski** [comment]
I’d rather not return `luhn_valid: true` in this case because it’s simply not true.

Another option would be to return `luhn_valid: null` (ie “doesn’t apply”). But that would break code that doesn’t do strict comparisons. Currently the only way to check if the card is valid is to check both `length_valid` and `luhn_valid`. So I imagine there’s a lot of code like this out there:

```
if (length_valid && luhn_valid) {
    // (...)
}

That would fail for cards that don’t require Luhn check.

In 1.0 there will be a new property: `valid`, which would take into account whether a Luhn check is required, but old code that uses the method above would be broken unfortunately.

**Pull request closed without merging**
